name: Kanban Task
description: Create a task for the Kanban board
title: "[TASK] "
labels: [task, kanban]
body:
  - type: markdown
    attributes:
      value: |
        Please provide details for this Kanban board task.
  - type: input
    id: summary
    attributes:
      label: Task Summary
      description: Briefly describe the task.
      placeholder: "Implement user login"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Task Details
      description: Provide more context, requirements, or acceptance criteria.
      placeholder: "Describe what needs to be done, dependencies, etc."
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level.
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: input
    id: assignees
    attributes:
      label: Assignees
      description: Who will work on this? (GitHub usernames)
      placeholder: "username1, username2"
    validations:
      required: false
  - type: input
    id: due_date
    attributes:
      label: Due Date
      description: When should this task be finished? (YYYY-MM-DD)
      placeholder: "2025-06-15"
    validations:
      required: false
