name: Kanban Task
description: Create a task for the Kanban board
title: "[TASK] "
labels: [task, kanban]
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 New Task for the Kanban Board
        Complete the information below to create a new task in the project.

  - type: input
    id: summary
    attributes:
      label: Task Summary
      description: Briefly describe the task.
      placeholder: "Implement user login functionality"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: Task Details
      description: Provide more context, requirements, or acceptance criteria.
      placeholder: "Describe what needs to be done, dependencies, technical requirements, etc."
    validations:
      required: false

  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: Select the priority level for this task.
      options:
        - P0 (Critical)
        - P1 (High)
        - P2 (Medium)
        - P3 (Low)
    validations:
      required: true

  - type: dropdown
    id: status
    attributes:
      label: Initial Status
      description: Select the initial status for this task.
      options:
        - Backlog
        - In Progress
        - In Review
        - Done
      default: 0
    validations:
      required: true

  - type: dropdown
    id: task_type
    attributes:
      label: Task Type
      description: What type of task is this?
      options:
        - Feature
        - Bug Fix
        - Enhancement
        - Documentation
        - Refactoring
        - Testing
    validations:
      required: true

  - type: input
    id: estimated_hours
    attributes:
      label: Estimated Hours
      description: How many hours do you estimate this task will take?
      placeholder: "8"
    validations:
      required: false
