name: Kanban Task
description: Create a task for the Kanban board
title: "[TASK] "
labels: [task, kanban]
body:
  - type: markdown
    attributes:
      value: |
        ## 📋 New Task for the Kanban Board
        Complete the information below to create a new task in the project.

  - type: input
    id: summary
    attributes:
      label: 📝 Task Summary
      description: Briefly describe the task.
      placeholder: "Implement user login functionality"
    validations:
      required: true

  - type: textarea
    id: details
    attributes:
      label: 📌 Task Details
      description: Use the checklist format to list subtasks or steps.
      placeholder: |
        - [ ] Define database schema
        - [ ] Set up backend endpoints
        - [ ] Create frontend form
        - [ ] Test login flow
    validations:
      required: false
