name: Kanban Task
description: Create a task card for the Kanban board
title: "[TASK] "
labels: [task, kanban]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the following details to create a new Kanban task.
  - type: input
    id: summary
    attributes:
      label: Task Summary
      description: Briefly describe the task.
      placeholder: "Implement user login"
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Task Details
      description: Provide more details, context, or requirements for this task.
      placeholder: "Describe what needs to be done, acceptance criteria, dependencies, etc."
    validations:
      required: false
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Select the priority level for this task.
      options:
        - Low
        - Medium
        - High
    validations:
      required: true
  - type: input
    id: assignees
    attributes:
      label: Assignees
      description: Who is responsible for this task? (GitHub usernames, comma-separated)
      placeholder: "username1, username2"
    validations:
      required: false
  - type: input
    id: due_date
    attributes:
      label: Due Date
      description: When should this task be completed? (optional, format: YYYY-MM-DD)
      placeholder: "2025-06-15"
    validations:
      required: false
